# Site settings
title: ismaro3.github.io
url: "http://ismaro3.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: '' # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Europe/Madrid
description: >
  Blog de mis proyectos de programación

# Your information
email: ismaro.394@gmail.com
author: Ismael Rodríguez
avatar: "//www.gravatar.com/avatar/4de8d654bf7cffcbd7bbc18fd3bc1e34?d=mm&s=135"
profile: Estudiante de Ingeniería Informática
#twitter_username: ismaro3
github_username:  ismaro3

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: ismaro3githubio   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
